[versions]
agp = "8.5.2"
appcompatVersion = "1.7.0"
coreKtxVersion = "1.13.1"
espressoCore = "3.6.1"
glide = "4.15.1"
gson = "2.10.1"
hiltAndroidVersion = "2.51.1"
hiltCompiler = "2.51.1"
javaWebsocket = "1.5.3"
junit = "4.13.2"
kotlin = "1.9.0"
coreKtx = "1.13.1"
constraintlayout = "2.1.4"
# WebRTC
coroutines = "1.8.1"
materialVersion = "1.12.0"
webrtc = "1.0.5"
junitKtx = "1.2.1"

[libraries]
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx-v170 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android-v244 = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-compiler-v244 = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }
junit-v4132 = { module = "junit:junit", version.ref = "junit" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# WebRTC
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
webrtc = { module = "com.mesibo.api:webrtc", version.ref = "webrtc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

